### ISSUE TITLE
大佬可以抽空更新一下吗

### ISSUE THREAD

**Issue by BA7IEE** [ExerciseBook/fof-upload-imagex#2]
Flarum 1.8.8
Fancybox 2.0.2

上传的时候使用了ImageX 图像预览模板之后，图片不支持点击了，Fancybox无效

**Comment by BA7IEE** [comment]
我修改了下代码，图片好像支持fancybox了，先用用试试
看了下Fancybox代码，应该是需要图片被包裹在<a>标签中才能工作

```
// resources/templates/imagex-preview.blade.php
// <img src="{@preview_uri}" data-src="{@fullscreen_uri}" title="{@base_name}" alt="{@base_name}"/>

<a href="{@fullscreen_uri}" data-fancybox="gallery">
  <img src="{@preview_uri}" alt="{@base_name}"/>
</a>
```

**Comment by ExerciseBook** [comment]
你方便改好之后 pr 过来嘛。我最近有点忙。

就是说现在的 fancybox 要求要挂一个标签才行。我去看一眼 fancybox 的代码。


---

https://github.com/iamdarkle/fancybox/blame/36df8eb361bec4fe2f6411661f8612e29a265ede/js/src/forum/index.js#L30

确实是新加的。我处理一下。

**Comment by ExerciseBook** [comment]
那我处理一下吧。感觉我得找个合理一点的方案。

**Comment by ExerciseBook** [comment]
试一下最新分支里的 commit 看看能不能成。用 `composer require :dev-master` 试试。

---

来自 flarum 中文群里的一些信息。fancybox 2 有点奇怪的问题，可能我短时间内不会发 release，可以先在 dev 里试试。有啥问题随时回复。

**Comment by ExerciseBook** [comment]
现在应该没问题了，我直接 close 掉了。发布了 1.6
